name = "prime"
version = "0.1.0"
license = "MIT"
author = "Wayne.MJ"
maintainer = "150761502+wayne-mj@users.noreply.github.com"
copyright = "Copyright 2025, Wayne.MJ"
description = "Prime number generator"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dev-dependencies]
VerySimpleTestFramework.git = "https://github.com/wayne-mj/VerySimpleTestFramework.git"

